# Generated by Django 3.2.23 on 2023-12-27 19:48

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='new event1', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='hostId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='user_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
