# Generated by Django 3.2.23 on 2023-12-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0003_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
