# Generated by Django 3.2.23 on 2023-12-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0004_remove_event_attendees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
