# Generated by Django 3.2.23 on 2023-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennisApp', '0009_alter_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hostId',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
